/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    borderRadius: {
      none: '0',
      sm: '4px',
      DEFAULT: '6px',
      md: '8px',
      lg: '8px',
      xl: '8px',
      '2xl': '8px',
      '3xl': '8px',
      full: '9999px',
    },
    extend: {
      colors: {
        navy: {
          950: '#090E1A',
          900: '#0D1526',
          800: '#132038',
          700: '#1A2E50',
          600: '#243D6A',
          500: '#2E4E88',
        },
        emerald: {
          DEFAULT: '#34C759',
          50:  '#EAF8EF',
          100: '#D8F4E0',
          200: '#B6E8C4',
          300: '#8DDAA2',
          400: '#5ED17D',
          500: '#34C759',
          600: '#248A3D',
          700: '#1F6F34',
          800: '#174F27',
          900: '#0D2F18',
        },
        gold: {
          DEFAULT: '#FFCC00',
          50:  '#FFFBE6',
          100: '#FFF6CC',
          200: '#FFEE99',
          300: '#FFE166',
          400: '#FFD633',
          500: '#FFCC00',
          600: '#B28F00',
          700: '#8A6D00',
          800: '#5C4900',
          900: '#332800',
        },
        success: '#1B7F3A',
        warning: '#B45309',
        danger:  '#C41E16',
        info:    '#0071E3',
      },
      fontFamily: {
        display: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"SF Pro Display"',
          '"Helvetica Neue"',
          'Helvetica',
          'Arial',
          'system-ui',
          'sans-serif',
        ],
        sans: [
          '-apple-system',
          'BlinkMacSystemFont',
          '"SF Pro Text"',
          '"SF Pro Display"',
          '"Helvetica Neue"',
          'Helvetica',
          'Arial',
          'system-ui',
          'sans-serif',
        ],
        mono: ['"SF Mono"', 'SFMono-Regular', 'ui-monospace', 'Menlo', 'Consolas', 'monospace'],
      },
      letterSpacing: {
        apple: '-0.011em',
        'apple-tight': '-0.022em',
      },
      fontSize: {
        '2xs': ['0.6875rem', { lineHeight: '1rem', letterSpacing: '0.006em' }],
        xs:    ['0.8125rem', { lineHeight: '1.125rem', letterSpacing: '0.006em' }],
        sm:    ['0.9375rem', { lineHeight: '1.25rem', letterSpacing: '-0.006em' }],
        base:  ['1.0625rem', { lineHeight: '1.5rem', letterSpacing: '-0.011em' }],
        lg:    ['1.125rem',  { lineHeight: '1.625rem', letterSpacing: '-0.014em' }],
        xl:    ['1.25rem',   { lineHeight: '1.75rem', letterSpacing: '-0.017em' }],
        '2xl': ['1.5rem',    { lineHeight: '2rem', letterSpacing: '-0.019em' }],
        '3xl': ['1.75rem',   { lineHeight: '2.125rem', letterSpacing: '-0.021em' }],
        '4xl': ['2.25rem',   { lineHeight: '2.5rem', letterSpacing: '-0.022em' }],
        '5xl': ['3rem',      { lineHeight: '1.05', letterSpacing: '-0.024em' }],
      },
      screens: {
        xs:  '480px',
        sm:  '640px',
        md:  '768px',
        lg:  '1024px',
        xl:  '1280px',
        '2xl': '1536px',
      },
      spacing: {
        '4.5': '1.125rem',
        13:  '3.25rem',
        15:  '3.75rem',
        18:  '4.5rem',
        22:  '5.5rem',
        72:  '18rem',
        80:  '20rem',
        88:  '22rem',
        96:  '24rem',
      },
      backdropBlur: {
        xs: '2px',
      },
      boxShadow: {
        card:          'var(--shadow-soft)',
        'card-hover':  'var(--shadow-hover)',
      },
      animation: {
        'fade-in':       'fadeIn 0.2s ease-out',
        'fade-up':       'fadeUp 0.3s ease-out',
        'slide-in-left': 'slideInLeft 0.3s ease-out',
        'slide-in-right':'slideInRight 0.3s ease-out',
        'scale-in':      'scaleIn 0.2s ease-out',
        'pulse-soft':    'pulseSoft 2s ease-in-out infinite',
        shimmer:         'shimmer 1.5s linear infinite',
        'spin-slow':     'spin 3s linear infinite',
      },
      keyframes: {
        fadeIn: {
          from: { opacity: '0' },
          to:   { opacity: '1' },
        },
        fadeUp: {
          from: { opacity: '0', transform: 'translateY(12px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
        slideInLeft: {
          from: { opacity: '0', transform: 'translateX(-20px)' },
          to:   { opacity: '1', transform: 'translateX(0)' },
        },
        slideInRight: {
          from: { opacity: '0', transform: 'translateX(20px)' },
          to:   { opacity: '1', transform: 'translateX(0)' },
        },
        scaleIn: {
          from: { opacity: '0', transform: 'scale(0.95)' },
          to:   { opacity: '1', transform: 'scale(1)' },
        },
        pulseSoft: {
          '0%, 100%': { opacity: '1' },
          '50%':      { opacity: '0.6' },
        },
        shimmer: {
          from: { backgroundPosition: '-200% 0' },
          to:   { backgroundPosition: '200% 0' },
        },
      },
      transitionDuration: {
        200: '200ms',
        300: '300ms',
      },
      transitionTimingFunction: {
        smooth: 'cubic-bezier(0.4, 0, 0.2, 1)',
      },
      backgroundImage: {
        'shimmer-base': 'linear-gradient(90deg, transparent 0%, rgba(255,255,255,0.7) 50%, transparent 100%)',
      },
    },
  },
  plugins: [],
};
